//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiSatisOtomasyonu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UcakBiletiSatisOtomasyonu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _150_1509062_transparent_text_message_icon_png_message_icon_png {
            get {
                object obj = ResourceManager.GetObject("150-1509062_transparent-text-message-icon-png-message-icon-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2021in_en_pahali_ucak_bileti_aciklandi_gidis_donus_32_bin_tl_7524_dhaphoto2 {
            get {
                object obj = ResourceManager.GetObject("2021in-en-pahali-ucak-bileti-aciklandi-gidis-donus-32-bin-tl_7524_dhaphoto2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23_236356_administrator_admin_icon_admin_icons_hd_png_download {
            get {
                object obj = ResourceManager.GetObject("23-236356_administrator-admin-icon-admin-icons-hd-png-download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _271_thy {
            get {
                object obj = ResourceManager.GetObject("271_thy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _354855 {
            get {
                object obj = ResourceManager.GetObject("354855", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37_373951_login_logo_de_login {
            get {
                object obj = ResourceManager.GetObject("37-373951_login-logo-de-login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37_373951_login_logo_de_login1 {
            get {
                object obj = ResourceManager.GetObject("37-373951_login-logo-de-login1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37_373951_login_logo_de_login2 {
            get {
                object obj = ResourceManager.GetObject("37-373951_login-logo-de-login2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _699_6997452_administrator_network_icons_system_avatar_computer_transparent_admin {
            get {
                object obj = ResourceManager.GetObject("699-6997452_administrator-network-icons-system-avatar-computer-transparent-admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _783_email {
            get {
                object obj = ResourceManager.GetObject("783_email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _988680_620x410 {
            get {
                object obj = ResourceManager.GetObject("988680_620x410", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap admin_icon_trendy_design_style_isolated_white_background_vector_simple_modern_flat_symbol_web_site_mobile_logo_app_135742404 {
            get {
                object obj = ResourceManager.GetObject("admin-icon-trendy-design-style-isolated-white-background-vector-simple-modern-fla" +
                        "t-symbol-web-site-mobile-logo-app-135742404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap air_ticket_162507919 {
            get {
                object obj = ResourceManager.GetObject("air-ticket-162507919", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap air_ticket_1625079191 {
            get {
                object obj = ResourceManager.GetObject("air-ticket-1625079191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap air_tickets_shows_aircraft_flights_3d_rendering {
            get {
                object obj = ResourceManager.GetObject("air-tickets-shows-aircraft-flights-3d-rendering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap anadolujet_logo {
            get {
                object obj = ResourceManager.GetObject("anadolujet_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap android_messages_logo_020799A598_seeklogo_com {
            get {
                object obj = ResourceManager.GetObject("android-messages-logo-020799A598-seeklogo.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CNT_Intel_Plane_Tickets_072018_TM_Detwiler {
            get {
                object obj = ResourceManager.GetObject("CNT_Intel_Plane Tickets_072018_TM Detwiler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crystal_Clear_action_exit_svg {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_exit.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_40575109_stock_illustration_login_button {
            get {
                object obj = ResourceManager.GetObject("depositphotos_40575109-stock-illustration-login-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_40575109_stock_illustration_login_button1 {
            get {
                object obj = ResourceManager.GetObject("depositphotos_40575109-stock-illustration-login-button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Emblem_question_red_svg {
            get {
                object obj = ResourceManager.GetObject("Emblem-question-red.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gökyüzü {
            get {
                object obj = ResourceManager.GetObject("gökyüzü", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gokyuzu_neden_mavidir_22 {
            get {
                object obj = ResourceManager.GetObject("gokyuzu-neden-mavidir-22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Google_Messages_logo_svg {
            get {
                object obj = ResourceManager.GetObject("Google_Messages_logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap indir {
            get {
                object obj = ResourceManager.GetObject("indir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1016073730_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1016073730-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1137971264_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1137971264-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1177861857_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1177861857-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kapak_144819 {
            get {
                object obj = ResourceManager.GetObject("kapak_144819", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kapak_144819__1_ {
            get {
                object obj = ResourceManager.GetObject("kapak_144819 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kapak_1448191 {
            get {
                object obj = ResourceManager.GetObject("kapak_1448191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_airline_ticket_5b3e6fa8cfe3e2_4735565215308184728515 {
            get {
                object obj = ResourceManager.GetObject("kisspng-airline-ticket-5b3e6fa8cfe3e2.4735565215308184728515", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_airplane_flight_airline_ticket_boarding_pass_trave_boarding_pass_5ada61bc4e33c6_5262718215242613083203 {
            get {
                object obj = ResourceManager.GetObject("kisspng-airplane-flight-airline-ticket-boarding-pass-trave-boarding-pass-5ada61bc" +
                        "4e33c6.5262718215242613083203", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_button_png_12 {
            get {
                object obj = ResourceManager.GetObject("login-button-png-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mavi_gokyuzu {
            get {
                object obj = ResourceManager.GetObject("mavi-gokyuzu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pegasus_Airlines_logo_239FB5E288_seeklogo_com {
            get {
                object obj = ResourceManager.GetObject("Pegasus_Airlines-logo-239FB5E288-seeklogo.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pegasus_Airlines_logo_239FB5E288_seeklogo1 {
            get {
                object obj = ResourceManager.GetObject("Pegasus_Airlines-logo-239FB5E288-seeklogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap personel {
            get {
                object obj = ResourceManager.GetObject("personel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap personel_1030x438 {
            get {
                object obj = ResourceManager.GetObject("personel-1030x438", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plane_ticket_icon_design_vector_22049102 {
            get {
                object obj = ResourceManager.GetObject("plane-ticket-icon-design-vector-22049102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_exit_sign_emergency_exit_computer_icons_graphy_others_text_photography_trademark {
            get {
                object obj = ResourceManager.GetObject("png-transparent-exit-sign-emergency-exit-computer-icons-graphy-others-text-photog" +
                        "raphy-trademark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_exit_sign_emergency_exit_computer_icons_graphy_others_text_photography_trademark1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-exit-sign-emergency-exit-computer-icons-graphy-others-text-photog" +
                        "raphy-trademark1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_exit_sign_emergency_exit_computer_icons_graphy_others_text_photography_trademark2 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-exit-sign-emergency-exit-computer-icons-graphy-others-text-photog" +
                        "raphy-trademark2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_social_media_linkedin_business_organization_company_plane_angle_company_logo {
            get {
                object obj = ResourceManager.GetObject("png-transparent-social-media-linkedin-business-organization-company-plane-angle-c" +
                        "ompany-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thy_4265 {
            get {
                object obj = ResourceManager.GetObject("thy_4265", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thy_42651 {
            get {
                object obj = ResourceManager.GetObject("thy_42651", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tickets_for_domestic_flights_only_airline_ticket_11563257210fp3vlxv1vp {
            get {
                object obj = ResourceManager.GetObject("tickets-for-domestic-flights-only-airline-ticket-11563257210fp3vlxv1vp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uçak {
            get {
                object obj = ResourceManager.GetObject("uçak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ucak_700x420 {
            get {
                object obj = ResourceManager.GetObject("Ucak-700x420", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uçak_havada_e1562154395731 {
            get {
                object obj = ResourceManager.GetObject("uçak-havada-e1562154395731", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ucak_modelleri {
            get {
                object obj = ResourceManager.GetObject("ucak-modelleri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ucak_modelleri1 {
            get {
                object obj = ResourceManager.GetObject("ucak-modelleri1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ucak_ucmak {
            get {
                object obj = ResourceManager.GetObject("ucak_ucmak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ucaklar_nasil_ucar_3 {
            get {
                object obj = ResourceManager.GetObject("ucaklar-nasil-ucar-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ucuslar_ne_zaman_shutter_16_9_1589535742_880x495 {
            get {
                object obj = ResourceManager.GetObject("ucuslar-ne-zaman-shutter_16_9_1589535742-880x495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
